"""Durable run records for taskboard-spawned sessions."""

from __future__ import annotations

import json
import os
import re
import tempfile
import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


RUN_STATUSES = {"accepted", "starting", "running", "completed", "failed", "aborted"}
_TASK_ID_PATTERNS = (
    re.compile(r"\btask[-_ ](?P<id>\d+)\b", re.IGNORECASE),
    re.compile(r"\bTask\s+#(?P<id>\d+)\b", re.IGNORECASE),
    re.compile(r"\B#(?P<id>\d+)\b"),
)
_TOKEN_GENERATION_PATTERNS = (
    re.compile(
        r"\btoken=(?P<token>[A-Za-z0-9_.:-]+)&generation=(?P<generation>\d+)\b"
    ),
    re.compile(
        r"\bstart-work\s+\d+\s+\"[^\"]+\"\s+"
        r"(?P<token>[A-Za-z0-9_.:-]+)\s+(?P<generation>\d+)\b"
    ),
    re.compile(
        r"\b--token\s+(?P<token>[A-Za-z0-9_.:-]+)\s+"
        r"--generation\s+(?P<generation>\d+)\b"
    ),
)


def utc_now() -> str:
    """Return a UTC ISO timestamp.

    Returns:
        ISO-8601 UTC timestamp with ``Z`` suffix.
    """

    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace(
        "+00:00", "Z"
    )


def extract_task_id(*values: str) -> int | None:
    """Extract a task id from labels/prompts when taskboard does not send one.

    Args:
        *values: Candidate strings such as labels, prompts, and titles.

    Returns:
        First task id found, otherwise ``None``.
    """

    for value in values:
        text = str(value or "")
        for pattern in _TASK_ID_PATTERNS:
            match = pattern.search(text)
            if match:
                return int(match.group("id"))
    return None


def extract_session_binding(prompt: str) -> tuple[str, int | None]:
    """Extract taskboard session token/generation from a spawn prompt.

    Args:
        prompt: Taskboard-generated task prompt.

    Returns:
        Pair of session token and generation. Missing values return
        ``("", None)``.
    """

    text = str(prompt or "")
    for pattern in _TOKEN_GENERATION_PATTERNS:
        match = pattern.search(text)
        if match:
            return match.group("token"), int(match.group("generation"))
    return "", None


@dataclass
class TaskboardRun:
    """Durable metadata for one taskboard-spawned run.

    Attributes:
        run_id: Stable run identifier generated by the gateway.
        session_key: OpenClaw-compatible session key exposed to taskboard.
        requested_agent_id: Agent id requested by the taskboard.
        local_agent_name: Local agent config name used for execution.
        prompt: Original task prompt.
        label: Human/session label supplied by taskboard.
        cleanup: Taskboard cleanup policy.
        task_id: Parsed task id when available.
        status: Current run lifecycle status.
        created_at: Run creation timestamp.
        updated_at: Last persistence timestamp.
        started_at: Start timestamp when execution begins.
        ended_at: Terminal timestamp.
        error: Last error if failed or aborted.
        final_text: Final model output preview.
        followups: Messages queued via ``sessions_send``.
        events: Bounded event log captured from the local session.
    """

    run_id: str
    session_key: str
    requested_agent_id: str
    local_agent_name: str
    prompt: str
    label: str
    cleanup: str = "keep"
    task_id: int | None = None
    status: str = "accepted"
    created_at: str = field(default_factory=utc_now)
    updated_at: str = field(default_factory=utc_now)
    started_at: str | None = None
    ended_at: str | None = None
    error: str | None = None
    final_text: str | None = None
    followups: list[dict[str, Any]] = field(default_factory=list)
    events: list[dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        """Serialize the run to a JSON-compatible dict.

        Returns:
            Dictionary representation of the run.
        """

        return asdict(self)

    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> "TaskboardRun":
        """Deserialize a run from a dict.

        Args:
            payload: Previously serialized run payload.

        Returns:
            Reconstructed run instance.
        """

        return cls(**payload)


class RunStore:
    """JSON-file backed run store.

    Args:
        root: Directory where run JSON records are stored.
    """

    def __init__(self, root: str | Path) -> None:
        self.root = Path(root)
        self.root.mkdir(parents=True, exist_ok=True)

    def create_run(
        self,
        *,
        requested_agent_id: str,
        local_agent_name: str,
        prompt: str,
        label: str,
        cleanup: str,
    ) -> TaskboardRun:
        """Create and persist a new accepted run.

        Args:
            requested_agent_id: Original taskboard agent id.
            local_agent_name: Local agent name selected for execution.
            prompt: Prompt to execute.
            label: Taskboard session label.
            cleanup: Cleanup policy supplied by taskboard.

        Returns:
            Newly persisted run.
        """

        run_id = f"run_{uuid.uuid4().hex[:16]}"
        task_id = extract_task_id(label, prompt)
        session_key = self._build_session_key(
            local_agent_name=local_agent_name,
            label=label,
            task_id=task_id,
            run_id=run_id,
        )
        run = TaskboardRun(
            run_id=run_id,
            session_key=session_key,
            requested_agent_id=requested_agent_id,
            local_agent_name=local_agent_name,
            prompt=prompt,
            label=label,
            cleanup=cleanup,
            task_id=task_id,
        )
        self.save(run)
        return run

    def save(self, run: TaskboardRun) -> None:
        """Persist a run atomically.

        Args:
            run: Run record to write.

        Raises:
            ValueError: If the run status is invalid.
        """

        if run.status not in RUN_STATUSES:
            raise ValueError(f"invalid run status: {run.status}")
        run.updated_at = utc_now()
        path = self.path_for(run.run_id)
        path.parent.mkdir(parents=True, exist_ok=True)
        fd, tmp_name = tempfile.mkstemp(
            dir=str(path.parent),
            prefix=f".{path.stem}.",
            suffix=".tmp",
        )
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as handle:
                json.dump(run.to_dict(), handle, indent=2, ensure_ascii=False)
            os.replace(tmp_name, path)
        finally:
            if os.path.exists(tmp_name):
                os.unlink(tmp_name)

    def get(self, run_id: str) -> TaskboardRun | None:
        """Load a run by id.

        Args:
            run_id: Run identifier.

        Returns:
            Run record when found, otherwise ``None``.
        """

        path = self.path_for(run_id)
        if not path.is_file():
            return None
        return TaskboardRun.from_dict(json.loads(path.read_text(encoding="utf-8")))

    def get_by_session_key(self, session_key: str) -> TaskboardRun | None:
        """Load a run by OpenClaw-compatible session key.

        Args:
            session_key: Session key exposed to the taskboard.

        Returns:
            Matching run when found, otherwise ``None``.
        """

        for run in self.list_runs(limit=None):
            if run.session_key == session_key:
                return run
        return None

    def list_runs(self, *, limit: int | None = 50) -> list[TaskboardRun]:
        """List runs ordered by most recent update.

        Args:
            limit: Maximum number of runs to return. ``None`` returns all.

        Returns:
            Recent run records.
        """

        runs: list[TaskboardRun] = []
        for path in self.root.glob("*.json"):
            try:
                runs.append(
                    TaskboardRun.from_dict(json.loads(path.read_text(encoding="utf-8")))
                )
            except (OSError, json.JSONDecodeError, TypeError, ValueError):
                continue
        runs.sort(key=lambda item: item.updated_at, reverse=True)
        return runs if limit is None else runs[: max(0, int(limit))]

    def update_status(
        self,
        run: TaskboardRun,
        status: str,
        *,
        error: str | None = None,
        final_text: str | None = None,
    ) -> TaskboardRun:
        """Update run lifecycle status and terminal metadata.

        Args:
            run: Run to update.
            status: New lifecycle status.
            error: Optional error message.
            final_text: Optional final response text.

        Returns:
            Updated run.
        """

        now = utc_now()
        run.status = status
        if status in {"starting", "running"} and run.started_at is None:
            run.started_at = now
        if status in {"completed", "failed", "aborted"}:
            run.ended_at = now
        if error is not None:
            run.error = error
        if final_text is not None:
            run.final_text = final_text
        self.save(run)
        return run

    def append_followup(self, run: TaskboardRun, message: str) -> TaskboardRun:
        """Append a follow-up message to a run.

        Args:
            run: Run receiving the follow-up.
            message: Message supplied through ``sessions_send``.

        Returns:
            Updated run.
        """

        run.followups.append({"message": message, "created_at": utc_now()})
        self.save(run)
        return run

    def append_event(self, run: TaskboardRun, event: dict[str, Any]) -> TaskboardRun:
        """Append one bounded event-log entry.

        Args:
            run: Run receiving the event.
            event: Session event to persist.

        Returns:
            Updated run.
        """

        run.events.append({"created_at": utc_now(), "event": event})
        if len(run.events) > 200:
            run.events = run.events[-200:]
        self.save(run)
        return run

    def path_for(self, run_id: str) -> Path:
        """Return the JSON path for a run id.

        Args:
            run_id: Run identifier.

        Returns:
            Path to the run JSON file.
        """

        safe = re.sub(r"[^a-zA-Z0-9_.-]", "-", run_id)
        return self.root / f"{safe}.json"

    @staticmethod
    def _build_session_key(
        *,
        local_agent_name: str,
        label: str,
        task_id: int | None,
        run_id: str,
    ) -> str:
        """Build an OpenClaw-compatible session key.

        Args:
            local_agent_name: Local agent name.
            label: Taskboard label.
            task_id: Parsed task id, if available.
            run_id: Gateway run id.

        Returns:
            Stable session key string.
        """

        slug_source = label or (f"task-{task_id}" if task_id is not None else run_id)
        slug = re.sub(r"[^a-zA-Z0-9_.-]+", "-", slug_source).strip("-") or run_id
        return f"agent:{local_agent_name}:{slug}:{run_id}"
